### ISSUE TITLE
multiplicity of oxygen molecules

### ISSUE THREAD

**Issue by njzjz** [aiqm/ANI1x_datasets#4]
I notice some oxygen molecules appears in the ANI-1x dataset, such as the oxygen dimer below. I'd like to confirm what multiplicity these dimers are using during the Gaussian calculation, 1 or 5?

```xyz
4

O 1.817700 0.308000 -0.269900
O 1.132200 -0.515000 0.285500
O -1.794600 -0.410600 -0.233300
O -1.155300 0.617600 0.217600
```

**Comment by isayev** [comment]
Yeah, it's one of the molecular outliers. In torchani while training the function `remove_outliers` should take care about it.

**Comment by zubatyuk** [comment]
All calculations for ANI datasets were performed with singlet spin
multiplicity.
